# Generated by Django 5.1.2 on 2024-10-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('Phone_Number', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Unnamed', max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(default='Add phone number', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('limit_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.hospital'),
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('Organ_id', models.AutoField(primary_key=True, serialize=False)),
                ('Organ_name', models.CharField(max_length=100)),
                ('organ_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.donor')),
            ],
        ),
        migrations.CreateModel(
            name='OrganTransplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.doctor')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.organ')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.insurance')),
            ],
        ),
        migrations.AddField(
            model_name='organ',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.patient'),
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('medicalreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy', models.CharField(max_length=255, null=True)),
                ('hereditary', models.CharField(max_length=255, null=True)),
                ('bloodtype', models.CharField(max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('consent_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('registration_no', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.driver')),
            ],
        ),
        migrations.AddField(
            model_name='organ',
            name='registration_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.transport'),
        ),
    ]
