# Generated by Django 5.1.2 on 2024-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
