# Generated by Django 5.1.2 on 2024-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_logininfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
