# Generated by Django 5.1.2 on 2024-10-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_logininfo_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
    ]
