# Generated by Django 5.1.2 on 2024-10-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_patient_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Age',
            new_name='patient_age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_gender',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default='jefin', max_length=250),
            preserve_default=False,
        ),
    ]
