# Generated by Django 5.1.2 on 2024-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_rename_age_patient_patient_age_remove_patient_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
