# Generated by Django 5.1.2 on 2024-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
