# Generated by Django 5.1.2 on 2024-11-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_appointments_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.organ'),
        ),
    ]
